# Generated by Django 3.1.7 on 2023-04-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_products_isbn_products_author_products_pubyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
