# Generated by Django 3.1.7 on 2023-04-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230403_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='susFlag',
            field=models.IntegerField(default=1),
        ),
    ]
