# Generated by Django 3.1.7 on 2023-04-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_products_susflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='susFlag',
            field=models.IntegerField(default=0),
        ),
    ]
