# Generated by Django 3.1.7 on 2023-04-08 02:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_delete_susmanage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Enter the genre for this category of book, max 50 characters', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(help_text='Enter email in name@provider.com format', max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(help_text='Enter first name, max 50 characters', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(help_text='Enter last name, max 50 characters', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(help_text='Enter password (in encrypted form)', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Enter phone number, do not include hyphens', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='susFlag',
            field=models.IntegerField(default=1, help_text='Set this to 0 for unsuspended, 1 for suspended'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', help_text='This is the customer address', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(help_text='This is the customer purchasing the book', on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime.today, help_text='This is the date the order was placed'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='This is the customer phone number', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(help_text='This is the price of one of this product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(help_text='This is the book title', on_delete=django.db.models.deletion.CASCADE, to='store.products'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1, help_text='This is the quantity of this partiuclar book purchased'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, help_text='Check this box to mark the order complete'),
        ),
        migrations.AlterField(
            model_name='products',
            name='ISBN',
            field=models.CharField(default='', help_text='Enter ISBN in ###-########## format.', max_length=14),
        ),
        migrations.AlterField(
            model_name='products',
            name='author',
            field=models.CharField(default='', help_text='Enter author name, max 60 characters', max_length=60),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, help_text='Enter author name, max 60 characters', on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Enter a description of the book, (Example: a summary)', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(help_text='Upload an image of the book cover (for display)', upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(help_text='Enter book Title, max 60 characters', max_length=60),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0.0, help_text='Enter price in float format (Example: 69.69)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pubYear',
            field=models.IntegerField(default=0, help_text='Enter publication year (Example: 2023)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='publisher',
            field=models.CharField(default='', help_text='Enter publisher name, max 60 characters', max_length=60),
        ),
        migrations.AlterField(
            model_name='products',
            name='susFlag',
            field=models.IntegerField(default=1, help_text='Set this to 0 for unsuspended, 1 for suspended'),
        ),
    ]
