# Generated by Django 3.1.7 on 2023-04-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='address',
        ),
    ]
