# Generated by Django 4.1.7 on 2023-04-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ISBN',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='products',
            name='author',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='products',
            name='pubYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='publisher',
            field=models.CharField(default='', max_length=60),
        ),
    ]
