# Generated by Django 3.1.7 on 2023-04-05 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_customer_susflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SusManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='susproduct', to='store.products')),
                ('susFlag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_susFlag', to='store.products')),
            ],
        ),
    ]
