# Generated by Django 3.1.7 on 2023-04-05 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_susmanage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SusManage',
        ),
    ]
